// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJ1n2WKc-LiK6yBBrw0wTLJECnX5r_HA',
    appId: '1:964526770624:web:e0fe7a146bf1b896f02025',
    messagingSenderId: '964526770624',
    projectId: 'david-psalmist',
    authDomain: 'david-psalmist.firebaseapp.com',
    storageBucket: 'david-psalmist.firebasestorage.app',
    measurementId: 'G-QH580MGB9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAE_kteJ5uhlqXpnWJ6CTkz-StsrQFfTg',
    appId: '1:964526770624:android:3f21942944c4ff00f02025',
    messagingSenderId: '964526770624',
    projectId: 'david-psalmist',
    storageBucket: 'david-psalmist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6oozQpW8s0N_ewJxoXrcyonetpRlsfs',
    appId: '1:964526770624:ios:30afcb36f3aa0dc7f02025',
    messagingSenderId: '964526770624',
    projectId: 'david-psalmist',
    storageBucket: 'david-psalmist.firebasestorage.app',
    iosBundleId: 'com.example.davidPsalmist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6oozQpW8s0N_ewJxoXrcyonetpRlsfs',
    appId: '1:964526770624:ios:30afcb36f3aa0dc7f02025',
    messagingSenderId: '964526770624',
    projectId: 'david-psalmist',
    storageBucket: 'david-psalmist.firebasestorage.app',
    iosBundleId: 'com.example.davidPsalmist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJ1n2WKc-LiK6yBBrw0wTLJECnX5r_HA',
    appId: '1:964526770624:web:d413eaefa930f470f02025',
    messagingSenderId: '964526770624',
    projectId: 'david-psalmist',
    authDomain: 'david-psalmist.firebaseapp.com',
    storageBucket: 'david-psalmist.firebasestorage.app',
    measurementId: 'G-KESZ8H20DF',
  );
}
